version: '3'

tasks:
  default:
    cmds:
      - echo 'Hello, AtCoder!'

  login:
    desc: 'AtCoder にログインする'
    cmds:
      - acc login
  join:
    desc: 'AtCorder の任意のコンテストに参加する ex: task join -- abc123'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - acc --template go-template new {{.CLI_ARGS }}

  add:
    desc: 'AtCoder の任意のコンテストの問題を追加する'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - acc --template go-template add

  test:
    desc: 'AtCoder の任意のコンテストのテストを実行する'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - oj t -c 'go run main.go' -d tests

  submit:
    desc: 'AtCoder の任意のコンテストの提出を行う'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - acc submit
